### ISSUE TITLE
avr/io.h lacked in FreeRTOS

### ISSUE THREAD

**Issue by jackjeanab** [MediaTek-Labs/Arduino-Add-On-for-LinkIt-SDK#104]
## Environment

 - Arduino BSP Version:v0.10.21
 - OS(Windows/macOS/Linux): windows 10
 - Additional external peripherals:No

error message as follow:
Arduino: 1.8.5 (Windows 10), Board: "LinkIt 7697"

In file included from C:\Users\Jack\Documents\Arduino\libraries\FreeRTOS\src/Arduino_FreeRTOS.h:53:0,

                 from C:\Users\Jack\Documents\Arduino\libraries\FreeRTOS\examples\AnalogRead_DigitalRead\AnalogRead_DigitalRead.ino:1:

C:\Users\Jack\Documents\Arduino\libraries\FreeRTOS\src/FreeRTOSConfig.h:32:20: fatal error: avr/io.h: No such file or directory

 #include <avr/io.h>

                    ^

compilation terminated.

exit status 1
Error compiling for board LinkIt 7697.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by pablosun** [comment]
因為MT7697並不是AVR架構而是ARM Cortex-M架構，所以是無法提供 avr/io 的，可能要請您自行檢查一下是為什麼會走到AVR那條路去。

另外，如果要用 FreeRTOS的 API 的話，LinkIt 7697 底層已經是用FreeRTOS了，應該不需要再從外部引入其他的FreeRTOS，這樣可能會造成名稱的衝突。

**Comment by jackjeanab** [comment]
收到  謝謝

Pablo Sun <notifications@github.com> 於 2018年8月22日週三 上午8:18 寫道：
