### ISSUE TITLE
Arduino IDE 1.8.2 : Does not properly show upload progress bar

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/Arduino-Add-On-for-LinkIt-SDK#19]
![image](https://cloud.githubusercontent.com/assets/23159280/26432546/0749b6ea-412f-11e7-851e-c6475a8dd983.png)

**Comment by pablosun** [comment]
As of Arduino IDE 1.8.2, the **upload** stage for Arduino Uno/Yun does not show progress bar either. So mark this issue as `wontfix` first.
