### ISSUE TITLE
Could you please add SOFTAP function on Arduino IDE?

### ISSUE THREAD

**Issue by scolin912** [MediaTek-Labs/Arduino-Add-On-for-LinkIt-SDK#34]
Hi All,
I notice that LinkIt 7697 + Arduino IDE without SOFTAP function.

If possible, please add a SOFTAP function on Arduino IDE.

Scenario:
1. LinkIt 7697 turn to AP mode.
2. Smartphone --> setting --> wifi --> connect with LinkIt 7697.
3. Smartphone's APP send socket include my AP SSID and PASSWORD to LinkIt 7697.
4. LinkIt 7697 turn to station mode and setting SSID and PASSWORD connect to internet.

Maybe we need three function like below:
1. Set LinkIt 7697 AP SSID and PASSWORD for client to connect.
2. Stop LinkIt 7697 AP mode. 
3. Turn on LinkIt 7697 station mode.

Many thanks. ^ ^

**Comment by pablosun** [comment]
`softAP()` and `softAPdisconnect()` is now available in BSP v0.10.5.
