### ISSUE TITLE
Examples->LWiFi->ScanNetworks won't print specific AP if the BSSID starts with 0x00

### ISSUE THREAD

**Issue by AcSiPCCW** [MediaTek-Labs/Arduino-Add-On-for-LinkIt-SDK#71]
In ard_mtk.c, get_scan_list()
strlen((char*)ptr->bssid) would be zero if the BSSID starts with 0x00.

**Comment by pablosun** [comment]
Looks like a typo bug: the intention of the check should be checking the `ssid` instead of the `bssid`, as the BSSID is of fixed-length and should never be treated as text strings.
