### ISSUE TITLE
LBLEAddress constructor incorrectly initializes the m_addr private struct

### ISSUE THREAD

**Issue by sfyang** [MediaTek-Labs/Arduino-Add-On-for-LinkIt-SDK#88]
In commit  [651f479](https://github.com/MediaTek-Labs/Arduino-Add-On-for-LinkIt-SDK/commit/651f479c5f00df794e990795f2a18d534a880e96) which rewrote the constructor of the LBLEAddress class, the `memset()` call initializing the `m_addr` is called with incorrect parameters as `memset(&m_addr, sizeof(m_addr), 0);` instead of `memset(&m_addr, 0, sizeof(m_addr));`. This is effectively equal to not initialize the `m_addr` struct, and has not caused error by luck.

**Comment by pablosun** [comment]
Thanks for catching this! It will be fixed in the next release.

**Comment by pablosun** [comment]
Fixed in 5f69fc7
